/* Browser controller and Canvas renderer. Models live in engine.js. */
(() => {
  'use strict';
  const A=window.Arcade,$=id=>document.getElementById(id);
  const definitions={
    shooter:{title:'Afterlight',genre:'01 / SPACE SHOOTER',Model:A.Shooter,accent:'#d9ed99',missionTitle:'One ship. One way through.',mission:'Earn 1,000 points to face the Warden. Dodge its attacks and break its 32-point shield before your fuel runs out.',controls:[['Move','← → / A D'],['Fire','SPACE'],['Pause','P']],notes:['R = rapid fire for 8 seconds.','S = collision shield for 5 seconds.','F = restore 40 fuel.','Every enemy is worth 50 points.'],intro:'Move with the arrow keys. Hold Space to fire. Collect power-ups and defeat the Warden.',ending:'The flight is over.'},
    breakout:{title:'Break the Grid',genre:'02 / BRICK BREAKER',Model:A.Breakout,accent:'#dbc0f3',missionTitle:'Find your rhythm.',mission:'Clear all three brick layouts. You have three lives. Catch falling power-ups to take control of the next rebound.',controls:[['Move paddle','← → / A D'],['Launch ball','SPACE / TAP'],['Pause','P']],notes:['W = a wider paddle for 12 seconds.','L = a slower ball for 12 seconds.','T = sticky paddle; Space relaunches.','Hit near a paddle edge to change the angle.'],intro:'Move the paddle with the arrow keys. Press Space to launch the ball. Clear three stages.',ending:'Your run is over.'},
    maze:{title:'Golden Hour',genre:'03 / MAZE ESCAPE',Model:A.Maze,accent:'#ebbc78',missionTitle:'Leave nothing behind.',mission:'Collect all eight coins to unlock the exit. Every maze has a route out, but the guards will send you back to the entrance.',controls:[['Move','ARROWS / WASD'],['Pause','P']],notes:['Gold rings are coins. Collect all eight.','Cyan clocks add 30 seconds.','Coral guards patrol a straight corridor.','The exit lights up after the final coin.'],intro:'Find eight coins, avoid the guards, and reach the gate. Use arrows or WASD to move.',ending:'The golden hour has passed.'},
    keep:{title:'Signal Keep',genre:'04 / ORIGINAL TOWER DEFENSE',Model:A.Keep,accent:'#b6d6da',missionTitle:'Keep the signal alive.',mission:'Protect the relay through six waves. Place towers on the eight build pads, balance damage and slowing effects, and spend energy on upgrades.',controls:[['Select pulse / frost','1 / 2'],['Build or upgrade','CLICK PAD'],['Send next wave','ENTER'],['Pause','P']],notes:['Pulse towers cost 60 energy and deal damage.','Frost towers cost 45 and slow intruders.','Upgrades cost 50. Maximum level: 3.','Runners are quick; armored intruders take two integrity.'],intro:'Build your first towers before starting a wave. Combine Pulse damage with Frost slowing to protect the relay.',ending:'The relay went silent.'}
  };
  const id=new URLSearchParams(location.search).get('game')||'keep',key=definitions[id]?id:'keep',cfg=definitions[key],canvas=$('game'),ctx=canvas.getContext('2d');
  let model=new cfg.Model(),keys={},last=0,lastPaint=0,previousState='ready',endHandled=false,sound=false,audio=null,saved=false,storageOK=true,pointer=null,scoreList=[];
  const storageKey='rm-arcade-v1-'+key;
  try{scoreList=A.scores(localStorage.getItem(storageKey));}catch{storageOK=false;}
  document.title=cfg.title+' — Ricardo Moran · Ivelisse Wright · Nicole Edzaguirre | RM Arcade';$('title').textContent=cfg.title;$('genre').textContent=cfg.genre;$('mission-title').textContent=cfg.missionTitle;$('mission').textContent=cfg.mission;
  document.querySelectorAll('nav a').forEach(a=>{if(a.getAttribute('href').endsWith('='+key))a.setAttribute('aria-current','page');});
  for(const [action,shortcut]of cfg.controls){const div=document.createElement('div');div.className='control-row';const label=document.createElement('span');label.textContent=action;const k=document.createElement('kbd');k.textContent=shortcut;div.append(label,k);$('controls').append(div);}
  cfg.notes.forEach(note=>{const li=document.createElement('li');li.textContent=note;$('notes').append(li);});
  $('build-panel').hidden=key!=='keep';$('touch').hidden=key==='keep';if(key==='maze')document.querySelector('.touch-fire').hidden=true;else document.querySelectorAll('[data-key="ArrowUp"],[data-key="ArrowDown"]').forEach(b=>b.hidden=true);
  function updateScores(){const ol=$('scores');ol.replaceChildren();if(!scoreList.length){const p=document.createElement('p');p.textContent='No scores yet. Make the first run count.';ol.append(p);}else for(const s of scoreList){const li=document.createElement('li'),name=document.createElement('span'),score=document.createElement('strong');name.textContent=s.name;score.textContent=s.score.toLocaleString();li.append(name,score);ol.append(li);}$('storage-note').textContent=storageOK?'Saved in this browser.':'Storage unavailable. Scores last until this tab closes.';}
  function stat(label,value){const d=document.createElement('div');d.className='stat';const s=document.createElement('span'),v=document.createElement('strong');s.textContent=label;v.textContent=value;d.append(s,v);return d;}
  function refreshHUD(){let items=[['Score',model.score.toLocaleString()]];
    if(key==='shooter'){items.push(['Fuel',Math.ceil(model.player.fuel)+'%'],['Rapid',model.player.rapid>0?model.player.rapid.toFixed(1)+'s':'—'],['Shield',model.player.shield>0?model.player.shield.toFixed(1)+'s':'—']);}
    if(key==='breakout')items.push(['Lives','●'.repeat(model.lives)||'0'],['Stage',model.level+' / 3'],['Power',Object.keys(model.effects).filter(k=>model.effects[k]>0).join(' + ')||'—']);
    if(key==='maze')items.push(['Coins',model.collected+' / 8'],['Time',Math.floor(model.remaining/60)+':'+String(Math.floor(model.remaining%60)).padStart(2,'0')],['Gate',model.coins.length?'Locked':'Open']);
    if(key==='keep'){items.push(['Energy',model.energy],['Integrity',model.integrity+' / 15'],['Wave',model.wave+' / 6']);$('wave').disabled=model.waveActive||model.state!=='playing';$('wave').firstChild.textContent=model.waveActive?'Wave in progress ':'Send wave '+(model.wave+1)+' ';}
    $('hud').replaceChildren(...items.map(s=>stat(...s)));$('status').textContent=model.state==='paused'?'Paused':model.message||(model.state==='playing'?'In play':'Ready to play');
  }
  function showOverlay(title,text,kicker,button){$('overlay').hidden=false;$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('overlay-kicker').textContent=kicker;$('start').firstChild.textContent=button+' ';}
  function start(){if(model.state==='paused'){model.pause();$('overlay').hidden=true;keys={};$('pause').firstChild.textContent='Pause ';canvas.focus();return;}
    model=new cfg.Model();model.begin();keys={};pointer=null;last=performance.now();endHandled=false;saved=false;$('score-form').hidden=true;$('overlay').hidden=true;$('pause').disabled=false;$('pause').firstChild.textContent='Pause ';$('restart').disabled=false;selectTower('pulse');updatePads();refreshHUD();canvas.focus();}
  function pause(){model.pause();keys={};pointer=null;if(model.state==='paused'){showOverlay('Paused','Your run will be here when you’re ready.','TAKE A BREATHER','Resume');$('score-form').hidden=true;$('pause').firstChild.textContent='Resume ';}else if(model.state==='playing'){$('overlay').hidden=true;$('pause').firstChild.textContent='Pause ';canvas.focus();}refreshHUD();}
  function finish(){if(endHandled)return;endHandled=true;keys={};$('pause').disabled=true;const won=model.state==='won';showOverlay(won?'Mission complete':cfg.ending,'Final score: '+model.score.toLocaleString()+(won?' · Nicely played.':' · There is always another run.'),won?'YOU MADE IT':'END OF RUN','Play again');const qualifies=model.score>0&&(scoreList.length<5||model.score>scoreList[scoreList.length-1].score);$('score-form').hidden=!qualifies;updateScores();refreshHUD();}
  $('start').addEventListener('click',start);$('pause').addEventListener('click',pause);$('restart').addEventListener('click',start);
  $('score-form').addEventListener('submit',e=>{e.preventDefault();if(saved||!['over','won'].includes(model.state))return;const name=$('initials').value.trim().toUpperCase();if(!/^[A-Z0-9]{1,3}$/.test(name))return;scoreList=A.addScore(scoreList,name,model.score);try{localStorage.setItem(storageKey,JSON.stringify(scoreList));}catch{storageOK=false;}saved=true;$('score-form').hidden=true;updateScores();$('status').textContent=storageOK?'High score saved':'Score kept for this session';});
  $('sound').addEventListener('click',()=>{sound=!sound;if(sound){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});}catch{sound=false;}}$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));});
  function tone(event){if(!sound||!audio||audio.state!=='running')return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=event==='power'?620:event==='shoot'?310:event==='damage'?90:200;g.gain.setValueAtTime(.026,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.085);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.09);}
  function selectTower(type){if(key!=='keep')return;model.selected=type;document.querySelectorAll('[data-tower]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tower===type)));}
  function updatePads(){if(key!=='keep')return;$('pad-buttons').replaceChildren(...A.PADS.map((p,i)=>{const b=document.createElement('button');const t=model.towers.find(t=>t.pad===i);b.textContent='Pad '+(i+1)+(t?' · '+t.type+' L'+t.level:'');b.setAttribute('aria-label',t?'Upgrade '+t.type+' tower on pad '+(i+1):'Build '+model.selected+' tower on pad '+(i+1));b.addEventListener('click',()=>{model.build(i);refreshHUD();updatePads();});return b;}));}
  document.querySelectorAll('[data-tower]').forEach(b=>b.addEventListener('click',()=>{selectTower(b.dataset.tower);updatePads();}));$('wave').addEventListener('click',()=>{model.sendWave();refreshHUD();});
  function keydown(e){if(['INPUT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;const code=e.code;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(code))e.preventDefault();keys[code]=true;if(e.repeat)return;if(code==='KeyP'||code==='Escape'){if(['playing','paused'].includes(model.state))pause();}if(key==='keep'){if(code==='Digit1')selectTower('pulse');if(code==='Digit2')selectTower('frost');if(code==='Enter')model.sendWave();updatePads();}}
  window.addEventListener('keydown',keydown);window.addEventListener('keyup',e=>delete keys[e.code]);window.addEventListener('blur',()=>{keys={};if(model.state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&model.state==='playing')pause();});
  for(const button of document.querySelectorAll('[data-key]')){button.addEventListener('pointerdown',e=>{e.preventDefault();keys[button.dataset.key]=true;button.setPointerCapture(e.pointerId);});for(const name of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(name,()=>delete keys[button.dataset.key]);}
  function coordinates(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*A.W,y:(e.clientY-r.top)/r.height*A.H};}
  canvas.addEventListener('pointerdown',e=>{if(model.state!=='playing')return;canvas.focus();const p=coordinates(e);if(key==='keep'){const i=A.PADS.findIndex(t=>Math.hypot(t.x-p.x,t.y-p.y)<34);if(i>=0){model.build(i);refreshHUD();updatePads();}return;}if(key==='breakout')model.launch();if(['shooter','breakout'].includes(key)){pointer=p;canvas.setPointerCapture(e.pointerId);}});
  canvas.addEventListener('pointermove',e=>{if(pointer)pointer=coordinates(e);});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>pointer=null);
  // Original procedural vector artwork, no image downloads or external sprites.
  function rect(x,y,w,h,c,r=0){ctx.fillStyle=c;ctx.beginPath();if(r)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);ctx.fill();}
  function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
  function line(points,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();}
  function text(str,x,y,size=15,color='#e7eee1',align='left'){ctx.font=`500 ${size}px 'Space Grotesk', Arial`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(str,x,y);}
  function polygon(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fill();}
  function field(){rect(0,0,A.W,A.H,'#101d25');for(let i=0;i<75;i++){const x=(i*137+51)%900,y=((i*83+29)+model.time*(6+i%5))%600;circle(x,y,i%3===0?1.4:.65,i%3===0?'#6b8e89':'#37505a');}}
  function ship(x,y,w,h){polygon([[x+w/2,y],[x+w,y+h],[x+w/2,y+h-10],[x,y+h]],'#d9ed99');polygon([[x+w/2,y+12],[x+w/2+7,y+32],[x+w/2-7,y+32]],'#214851');polygon([[x+18,y+h-2],[x+24,y+h+15+Math.sin(model.time*30)*6],[x+30,y+h-2]],'#87c9c1');}
  function drawShooter(){field();const p=model.player;ship(p.x,p.y,p.w,p.h);if(p.shield>0){ctx.strokeStyle='#8fcac6';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x+24,p.y+24,39,0,Math.PI*2);ctx.stroke();}
    for(const b of model.bullets)rect(b.x,b.y,b.w,b.h,p.rapid>0?'#e5baff':'#e2efb0',3);
    for(const e of model.enemies){const x=e.x+21,y=e.y+21;if(e.type==='rock'){ctx.save();ctx.translate(x,y);ctx.rotate(model.time);polygon([[-21,-7],[-10,-23],[15,-18],[24,6],[5,23],[-17,17]],'#a28577');circle(-3,-2,7,'#755f58');ctx.restore();}else{polygon([[x,y-22],[x+22,y],[x,y+22],[x-22,y]],e.type==='chaser'?'#e6a391':'#c3a9e2');circle(x,y,6,'#27394a');}}
    for(const d of model.pickups){rect(d.x,d.y,d.w,d.h,d.type==='rapid'?'#d5b4ef':d.type==='fuel'?'#e2c076':'#a6d6d2',8);text(d.type==='rapid'?'R':d.type==='fuel'?'F':'S',d.x+15,d.y+21,18,'#182a32','center');}
    for(const s of model.shots)circle(s.x+5,s.y+7,7,'#f59b86');
    if(model.boss){const b=model.boss;polygon([[b.x,b.y+5],[b.x+45,b.y+15],[b.x+75,b.y],[b.x+105,b.y+15],[b.x+150,b.y+5],[b.x+125,b.y+60],[b.x+75,b.y+45],[b.x+25,b.y+60]],'#d3a2ac');circle(b.x+75,b.y+27,10,'#ffdbc4');text('THE WARDEN',450,24,12,'#d5abb4','center');rect(320,33,260,5,'#3f3541',2);rect(320,33,260*b.hp/b.maxHp,5,'#d4a0b0',2);}
    if(model.state==='ready'){for(let i=0;i<5;i++){circle(115+i*170,140+(i%2)*70,22,'#716357');}text('OUTER ORBIT / SECTOR 07',35,570,10,'#779b9c');}
  }
  function drawBreakout(){field();const colors=['#dcc0f0','#c8acd8','#acbad3','#a9cbba','#dbeaa9'];for(const b of model.bricks){rect(b.x,b.y+4,b.w,b.h,'#08121a',3);rect(b.x,b.y,b.w,b.h,colors[b.row],3);rect(b.x+4,b.y+3,b.w-8,2,'#ffffff55',1);}const p=model.paddle;rect(p.x,p.y,p.w,p.h,model.effects.sticky?'#e8cb7d':'#b7d6d8',7);circle(model.ball.x,model.ball.y,model.ball.r,'#edf1dd');circle(model.ball.x-2,model.ball.y-2,2,'white');for(const d of model.pickups){rect(d.x,d.y,24,24,'#e2c6ee',5);text({wide:'W',slow:'L',sticky:'T'}[d.type],d.x+12,d.y+17,14,'#29303b','center');}if(model.ball.attached&&model.state==='playing')text('SPACE OR TAP TO LAUNCH',450,480,12,'#bccfd0','center');}
  function drawMaze(){rect(0,0,900,600,'#15232a');const z=32,ox=50,oy=30;for(let y=0;y<17;y++)for(let x=0;x<25;x++){if(model.grid[y][x]){rect(ox+x*z,oy+y*z,z-2,z-2,'#304347',3);rect(ox+x*z,oy+y*z,z-2,3,'#496062',2);}else rect(ox+x*z,oy+y*z,z,z,'#172831');}
    const xy=p=>({x:ox+p.x*z+z/2,y:oy+p.y*z+z/2});let e=xy(model.exit);rect(e.x-12,e.y-12,24,24,model.coins.length?'#654e3c':'#b6d78b',4);text('↗',e.x,e.y+6,20,model.coins.length?'#a48669':'#21382a','center');
    for(const c of model.coins){const p=xy(c);ctx.strokeStyle='#edc47d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.stroke();circle(p.x,p.y,2,'#edc47d');}
    for(const c of model.boosts){const p=xy(c);circle(p.x,p.y,9,'#8fc5c9');line([{x:p.x,y:p.y-5},{x:p.x,y:p.y},{x:p.x+5,y:p.y}],'#16373e',2);}
    for(const g of model.guards){const p=xy(g);polygon([[p.x,p.y-10],[p.x+11,p.y],[p.x,p.y+10],[p.x-11,p.y]],'#e49380');}
    const p=xy(model.player);circle(p.x,p.y,10,model.invulnerable>0?'#f8f1c3':'#eabd69');circle(p.x+3,p.y-2,2,'#263b3d');text('ENTRANCE',55,585,10,'#91a7a5');text(model.coins.length?'COLLECT ALL COINS TO UNLOCK THE GATE':'GATE OPEN — FIND THE EXIT',845,585,10,'#a5b78e','right');
  }
  function drawKeep(){rect(0,0,900,600,'#13242c');for(let y=25;y<600;y+=38)for(let x=23;x<900;x+=38)circle(x,y,1,'#29424b');ctx.lineJoin='round';ctx.lineCap='round';line(A.PATH,'#3c5357',45);line(A.PATH,'#6b8280',1);ctx.setLineDash([5,18]);line(A.PATH,'#acbda14d',2);ctx.setLineDash([]);ctx.lineCap='butt';
    for(let i=0;i<A.PADS.length;i++){const p=A.PADS[i];circle(p.x,p.y,29,'#1d363e');ctx.strokeStyle='#739696';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,29,0,Math.PI*2);ctx.stroke();const t=model.towers.find(t=>t.pad===i);if(!t){text('+',p.x,p.y+6,24,'#94b6b4','center');text(String(i+1),p.x,p.y+46,11,'#7c9a9e','center');}else{circle(t.x,t.y,21,t.type==='pulse'?'#d3dfa9':'#9bcbdc');polygon([[t.x,t.y-18],[t.x+11,t.y+8],[t.x-11,t.y+8]],'#24434e');for(let l=0;l<t.level;l++)circle(t.x-8+l*8,t.y+35,2,'#d5e4c9');}}
    for(const e of model.enemies){circle(e.x,e.y,e.type==='armor'?14:10,e.type==='armor'?'#b79bbf':e.type==='runner'?'#e8c271':'#db9383');if(e.type==='armor'){ctx.strokeStyle='#e0c1e5';ctx.strokeRect(e.x-10,e.y-10,20,20);}rect(e.x-15,e.y-22,30,3,'#17272a');rect(e.x-15,e.y-22,30*Math.max(0,e.hp)/e.maxHp,3,e.slow>0?'#9bd8e3':'#e8c1ad');}
    for(const b of model.beams)line([{x:b.x,y:b.y},{x:b.tx,y:b.ty}],b.type==='pulse'?'#d8eaa2':'#9bdded',3);
    circle(850,535,31,'#293f41');circle(850,535,20,'#b5d8cc');circle(850,535,9,'#2b5159');text('RELAY',849,586,11,'#acc5be','center');text('INCOMING',25,94,10,'#b29a8a');if(!model.waveActive)text('BUILD / UPGRADE / SEND THE NEXT WAVE',450,565,13,'#a5bdb4','center');
  }
  function draw(){({shooter:drawShooter,breakout:drawBreakout,maze:drawMaze,keep:drawKeep}[key])();}
  function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;
    if(pointer&&model.state==='playing'){if(key==='shooter')model.player.x=A.clamp(pointer.x-24,0,852);if(key==='breakout')model.paddle.x=A.clamp(pointer.x-model.paddle.w/2,0,900-model.paddle.w);}
    const input={left:keys.ArrowLeft||keys.KeyA,right:keys.ArrowRight||keys.KeyD,up:keys.ArrowUp||keys.KeyW,down:keys.ArrowDown||keys.KeyS,fire:keys.Space||(pointer&&key==='shooter')};model.update(dt,input);if(model.events.length){tone(model.events[model.events.length-1]);model.events=[];}draw();
    if(now-lastPaint>120){refreshHUD();lastPaint=now;}if(model.state!==previousState){if(model.state==='over'||model.state==='won')finish();previousState=model.state;}requestAnimationFrame(frame);
  }
  updateScores();refreshHUD();updatePads();showOverlay(cfg.title,cfg.intro,'READY WHEN YOU ARE','Start game');requestAnimationFrame(frame);
})();
